import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#1E1E1E' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 5, backgroundColor: '#0A0A0A', borderBottomWidth: 1, borderBottomColor: '#222' }, 
  headerLeft: { flexDirection: 'row', alignItems: 'center' }, 
  title: { fontSize: 24, fontWeight: '900', color: '#FFFFFF', letterSpacing: -0.5 }, 
  proBadge: { backgroundColor: '#FFD700', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 5, marginLeft: 8 },
  titlePro: { fontSize: 10, fontWeight: 'bold', color: '#000' }, 
  menuButton: { padding: 5 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-start', alignItems: 'flex-end' }, menuBox: { width: 250, backgroundColor: '#2A2A2A', height: '100%', padding: 20, borderLeftWidth: 1, borderLeftColor: '#444', elevation: 10 }, menuHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 30, marginTop: 20 }, menuTitle: { color: '#FFF', fontSize: 20, fontWeight: 'bold' }, menuItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#333' }, menuItemAtivo: { backgroundColor: 'rgba(229, 9, 20, 0.1)', borderRadius: 10, paddingHorizontal: 10, borderBottomWidth: 0 }, menuItemText: { color: '#FFF', fontSize: 16, marginLeft: 15 }, menuItemTextAtivo: { color: '#E50914', fontWeight: 'bold' },
  studioTopHeader: { alignItems: 'center', marginTop: 20, marginBottom: 25 },
  iconGlow: { width: 65, height: 65, borderRadius: 35, backgroundColor: '#E50914', justifyContent: 'center', alignItems: 'center', elevation: 10, boxShadow: '0px 4px 10px rgba(229, 9, 20, 0.5)', marginBottom: 15 },
  studioTitle: { color: '#FFF', fontSize: 26, fontWeight: 'bold' },
  studioSub: { color: '#A0A0A0', fontSize: 14, marginTop: 5, textAlign: 'center' },
  uploadCard: { width: '95%', backgroundColor: '#1A1A1A', borderRadius: 15, padding: 20, borderWidth: 1, borderColor: '#333', elevation: 5, marginBottom: 10 },
  uploadBtnPrimary: { flexDirection: 'row', backgroundColor: '#E50914', paddingVertical: 14, paddingHorizontal: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  uploadBtnSecondary: { flexDirection: 'row', backgroundColor: '#FF9800', paddingVertical: 14, paddingHorizontal: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  uploadBtnText: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold' },
  fileNameText: { color: '#4CAF50', fontSize: 12, textAlign: 'center', marginTop: 8, fontStyle: 'italic' },
  divisorUpload: { height: 1, backgroundColor: '#333', marginVertical: 15 },
  
  modalCenterOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', alignItems: 'center' },
  qualidadeBox: { backgroundColor: '#2A2A2A', width: '85%', borderRadius: 15, padding: 25, elevation: 10, alignItems: 'center' },
  destinoBox: { backgroundColor: '#2A2A2A', width: '90%', borderRadius: 15, padding: 20, elevation: 10, alignItems: 'center', maxHeight: '80%' },
  qualidadeTitle: { fontSize: 22, fontWeight: 'bold', color: '#FFF', marginBottom: 5 }, qualidadeSubtitle: { fontSize: 14, color: '#A0A0A0', textAlign: 'center', marginBottom: 20 },
  qualidadeOptionsContainer: { width: '100%', marginBottom: 15 },
  qualidadeBtn: { backgroundColor: '#2196F3', paddingVertical: 12, borderRadius: 10, marginBottom: 10, alignItems: 'center' },
  qualidadeBtnAudio: { backgroundColor: '#4CAF50', paddingVertical: 12, borderRadius: 10, marginBottom: 10, alignItems: 'center' },
  qualidadeBtnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
  qualidadeCancelarBtn: { paddingVertical: 10, marginTop: 10 }, qualidadeCancelarText: { color: '#E50914', fontSize: 16, fontWeight: 'bold' },
  
  btnDestinoCelular: { flexDirection: 'row', backgroundColor: '#9C27B0', width: '100%', paddingVertical: 15, borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  divisorDestino: { color: '#777', marginVertical: 15, fontSize: 12, fontWeight: 'bold' },
  destinoPastasScroll: { width: '100%', maxHeight: 200 },
  btnDestinoPasta: { flexDirection: 'row', backgroundColor: '#333', width: '100%', paddingVertical: 12, paddingHorizontal: 15, borderRadius: 10, marginBottom: 10, alignItems: 'center' },

  mainArea: { alignItems: 'center', width: '100%', flex: 1, paddingHorizontal: 20, paddingTop: 10 }, button: { backgroundColor: '#E50914', paddingVertical: 12, paddingHorizontal: 30, borderRadius: 30, width: '90%', alignItems: 'center', elevation: 5, marginTop: 10 }, buttonLetra: { backgroundColor: '#FF9800' }, buttonText: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold' }, infoText: { marginTop: 5, color: '#A0A0A0', fontSize: 12, textAlign: 'center', marginBottom: 5 }, playerContainer: { alignItems: 'center', width: '100%', marginTop: 5, flex: 1 }, sliderContainer: { flexDirection: 'row', alignItems: 'center', width: '95%', marginVertical: 15 }, slider: { flex: 1, height: 40, marginHorizontal: 10 }, tempoText: { color: '#A0A0A0', fontSize: 14, fontWeight: 'bold' }, actionButtons: { flexDirection: 'row', gap: 10, flexWrap: 'wrap', justifyContent: 'center', marginBottom: 15 }, playButton: { backgroundColor: '#4CAF50', paddingVertical: 12, paddingHorizontal: 20, borderRadius: 25 }, pauseButton: { backgroundColor: '#E50914' }, playButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: 'bold' }, karaokeButton: { backgroundColor: '#9C27B0', paddingVertical: 12, paddingHorizontal: 20, borderRadius: 25 }, karaokeButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: 'bold' }, saveButton: { backgroundColor: '#2196F3', paddingVertical: 12, paddingHorizontal: 15, borderRadius: 25 }, voiceButton: { backgroundColor: '#673AB7', paddingVertical: 12, paddingHorizontal: 15, borderRadius: 25 }, saveButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: 'bold' }, loadingContainer: { alignItems: 'center', marginTop: 10 }, loadingText: { color: '#FFFFFF', fontSize: 16, marginTop: 15, fontWeight: 'bold' }, lyricsBox: { flex: 1, width: '100%', marginBottom: 20, backgroundColor: '#2A2A2A', borderRadius: 15, paddingHorizontal: 20, elevation: 5, overflow: 'hidden' }, lyricText: { color: '#757575', fontSize: 18, textAlign: 'center', marginVertical: 15, fontWeight: '500' }, lyricActive: { color: '#FFD700', fontSize: 24, fontWeight: 'bold', textShadowColor: 'rgba(255, 215, 0, 0.4)', textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 10 }, creatorToggleButton: { backgroundColor: '#607D8B', paddingVertical: 10, paddingHorizontal: 20, borderRadius: 20, marginTop: 5 }, creatorToggleText: { color: '#FFFFFF', fontWeight: 'bold' }, creatorBox: { flex: 1, width: '100%', alignItems: 'center', justifyContent: 'center', backgroundColor: '#37474F', borderRadius: 15, padding: 20, marginBottom: 20 }, creatorTitle: { fontSize: 22, color: '#FFD700', fontWeight: 'bold', marginBottom: 10 }, linhaDestaque: { fontSize: 24, color: '#FFFFFF', fontWeight: 'bold', textAlign: 'center', marginVertical: 20 }, linhaProxima: { fontSize: 14, color: '#90A4AE', textAlign: 'center', marginBottom: 20, fontStyle: 'italic' }, marcarButton: { backgroundColor: '#00C853', paddingVertical: 20, paddingHorizontal: 40, borderRadius: 40, elevation: 10, marginBottom: 30 }, marcarButtonText: { color: '#FFFFFF', fontSize: 20, fontWeight: 'bold' }, saveLrcButton: { backgroundColor: '#FF9800', paddingVertical: 12, paddingHorizontal: 25, borderRadius: 25, marginBottom: 15 }, saveLrcText: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold' }, cancelarText: { color: '#B0BEC5', textDecorationLine: 'underline', marginTop: 10 },

  proPlayerArea: { flex: 1, width: '100%', alignItems: 'center', padding: 15, paddingTop: 5 },
  searchContainer: { flexDirection: 'row', width: '100%', marginBottom: 10 }, inputWrapper: { flex: 1, position: 'relative', justifyContent: 'center' }, searchInput: { width: '100%', backgroundColor: '#2A2A2A', color: '#FFF', paddingHorizontal: 20, paddingRight: 40, borderRadius: 25, height: 45, fontSize: 14 }, clearInputIcon: { position: 'absolute', right: 15 }, searchButton: { backgroundColor: '#E50914', justifyContent: 'center', alignItems: 'center', paddingHorizontal: 20, borderRadius: 25, marginLeft: 10, elevation: 3 },
  resultsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 5, paddingHorizontal: 5 }, resultsHeaderText: { color: '#A0A0A0', fontSize: 14, fontWeight: 'bold' }, closeResultsButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#555', paddingVertical: 5, paddingHorizontal: 10, borderRadius: 15 }, closeResultsText: { color: '#FFF', fontSize: 12, marginLeft: 5, fontWeight: 'bold' },
  ytItem: { flexDirection: 'row', backgroundColor: '#2A2A2A', width: '100%', borderRadius: 10, padding: 10, marginVertical: 5, elevation: 2 }, ytThumbContainer: { position: 'relative', width: 100, height: 56, borderRadius: 5, overflow: 'hidden' }, ytThumb: { width: '100%', height: '100%', backgroundColor: '#000' }, playOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.4)' }, ytInfo: { flex: 1, marginLeft: 15, justifyContent: 'space-between' }, ytTitle: { color: '#FFF', fontSize: 13, fontWeight: 'bold' }, ytButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 5 }, ytBtnVideo: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#2196F3', paddingVertical: 4, paddingHorizontal: 10, borderRadius: 15, gap: 5 }, ytBtnAudio: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#4CAF50', paddingVertical: 4, paddingHorizontal: 10, borderRadius: 15, gap: 5 }, ytBtnText: { color: '#FFF', fontSize: 11, fontWeight: 'bold' },
  videoContainer: { width: '100%', flex: 1, marginTop: 10, alignItems: 'center' }, playerTopBar: { flexDirection: 'row', width: '100%', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10, paddingHorizontal: 5 }, infoTextPro: { color: '#FFF', fontSize: 16, fontWeight: 'bold', flex: 1, marginRight: 10 }, videoPlayer: { width: '100%', aspectRatio: 16 / 9, flexShrink: 1, borderRadius: 10, overflow: 'hidden', backgroundColor: '#000' },
  playlistControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 15, gap: 30, width: '100%' }, playlistCounterText: { color: '#A0A0A0', fontSize: 14, fontWeight: 'bold' },
  queueContainer: { flex: 1, width: '100%', marginTop: 20, backgroundColor: '#252525', borderRadius: 10, padding: 15 }, queueHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#333', paddingBottom: 10, marginBottom: 10 }, queueTitle: { color: '#FFF', fontSize: 16, fontWeight: 'bold' }, queueClearText: { color: '#E50914', fontSize: 12, fontWeight: 'bold', textDecorationLine: 'underline' }, queueItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#333' }, queueItemActive: { backgroundColor: 'rgba(255, 215, 0, 0.1)', borderRadius: 8, paddingHorizontal: 10, borderBottomWidth: 0 }, queueItemTouchable: { flex: 1, flexDirection: 'row', alignItems: 'center' }, queueItemText: { color: '#A0A0A0', fontSize: 14, flex: 1 }, queueItemTextActive: { color: '#FFD700', fontWeight: 'bold' }, emptyPlaylistContainer: { justifyContent: 'center', alignItems: 'center', paddingHorizontal: 40, paddingVertical: 20, marginTop: 10 }, emptyPlaylistText: { color: '#FFF', fontSize: 16, fontWeight: 'bold', textAlign: 'center' }, emptyPlaylistSub: { color: '#777', fontSize: 12, textAlign: 'center', marginTop: 5 },

  // === ESTILOS DA BIBLIOTECA ===
  biblioContainer: { flex: 1, padding: 15, backgroundColor: '#1E1E1E' },
  biblioHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  biblioTitle: { fontSize: 22, fontWeight: 'bold', color: '#FFF' },
  btnNovaPasta: { flexDirection: 'row', backgroundColor: '#4CAF50', paddingVertical: 8, paddingHorizontal: 15, borderRadius: 20, alignItems: 'center' },
  btnNovaPastaText: { color: '#FFF', fontWeight: 'bold', fontSize: 14 },
  emptyBiblio: { flex: 1, justifyContent: 'center', alignItems: 'center' }, emptyBiblioText: { color: '#777', fontSize: 16, marginTop: 10 },
  pastaCard: { flex: 1, margin: 10, backgroundColor: '#2A2A2A', borderRadius: 15, padding: 20, alignItems: 'center', elevation: 3, position: 'relative' },
  pastaName: { color: '#FFF', marginTop: 10, fontWeight: 'bold', fontSize: 16 },
  btnExcluirPasta: { position: 'absolute', top: 10, right: 10, padding: 5 },
  biblioHeaderDentro: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, paddingBottom: 15, borderBottomWidth: 1, borderBottomColor: '#333' },
  biblioTitleDentro: { fontSize: 20, fontWeight: 'bold', color: '#FFF', marginLeft: 10, maxWidth: '70%' },
  btnImportar: { flexDirection: 'row', backgroundColor: '#2196F3', paddingVertical: 8, paddingHorizontal: 15, borderRadius: 20, alignItems: 'center' },
  arquivoRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#2A2A2A', padding: 15, borderRadius: 10, marginBottom: 10 },
  arquivoInfo: { flex: 1, flexDirection: 'row', alignItems: 'center' }, arquivoName: { color: '#FFF', fontSize: 14, marginLeft: 15, flex: 1 },
  inputPasta: { backgroundColor: '#1E1E1E', width: '100%', color: '#FFF', paddingHorizontal: 15, borderRadius: 10, height: 50, fontSize: 16, borderWidth: 1, borderColor: '#444' },
  btnSalvarPasta: { backgroundColor: '#4CAF50', paddingVertical: 10, paddingHorizontal: 30, borderRadius: 10 }, btnSalvarPastaText: { color: '#FFF', fontWeight: 'bold', fontSize: 16 },

  // === ESTILOS NOVOS DOS FILTROS E MÉTODOS DE VISUALIZAÇÃO ===
  filtroContainer: { flexDirection: 'row', backgroundColor: '#2A2A2A', borderRadius: 20, padding: 4, marginRight: 15 },
  filtroBtn: { padding: 6, borderRadius: 15 },
  
  pastaBadgeInfo: { backgroundColor: 'rgba(0,0,0,0.4)', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, marginTop: 10, alignItems: 'center', width: '100%' },
  pastaInfoDetalhado: { color: '#B0BEC5', fontSize: 10, fontWeight: 'bold' },
  
  pastaCardCompacto: { flex: 1, margin: 5, backgroundColor: '#2A2A2A', borderRadius: 10, padding: 10, alignItems: 'center', elevation: 2, position: 'relative' },
  pastaNameCompacto: { color: '#FFF', marginTop: 5, fontWeight: 'bold', fontSize: 12, textAlign: 'center' },
  btnExcluirPastaCompacto: { position: 'absolute', top: 5, right: 5, padding: 3, backgroundColor: 'rgba(0,0,0,0.3)', borderRadius: 10 },
  
  pastaCardLista: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#2A2A2A', borderRadius: 10, padding: 15, marginBottom: 10, elevation: 2 },
  pastaNameLista: { color: '#FFF', fontWeight: 'bold', fontSize: 16 },
  pastaInfoLista: { color: '#A0A0A0', fontSize: 12, marginTop: 4, fontWeight: '600' },
  
  // === ESTILOS DO NOVO EDITOR LRC ===
  editorFullContainer: { flex: 1, width: '100%', backgroundColor: '#1E1E1E', overflow: 'hidden' },
  editorHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 15, backgroundColor: '#111', borderBottomWidth: 1, borderBottomColor: '#333' },
  editorTitle: { color: '#FFF', fontSize: 20, fontWeight: 'bold' },
  editorList: { flex: 1, width: '100%' },
  editorRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 5, borderBottomWidth: 1, borderBottomColor: '#2A2A2A' },
  editorRowActive: { backgroundColor: '#FF9800' },
  editorTimeBtn: { padding: 5 },
  editorTimeText: { color: '#FFCA28', width: 75, textAlign: 'center', fontSize: 13, fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  editorLyricText: { flex: 1, color: '#FFF', fontSize: 14, marginHorizontal: 10 },
  editorTextActive: { color: '#000', fontWeight: 'bold' },
  editorActionBtn: { padding: 10 },
  editorBottomBar: { backgroundColor: '#222', padding: 15, borderTopWidth: 1, borderTopColor: '#333' },
  editorSongTitle: { color: '#FF9800', fontSize: 14, fontWeight: 'bold', textAlign: 'center', marginBottom: 10 },
  editorSliderContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  editorControls: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 10 },
  editorControlBtn: { padding: 5 },
  markButtonNovo: { backgroundColor: '#FF9800', paddingVertical: 12, paddingHorizontal: 30, borderRadius: 5, elevation: 3 },
  markButtonText: { color: '#000', fontSize: 16, fontWeight: 'bold' },
  // === ESTILOS DA TELA DE METADADOS LRC ===
  metaContainer: { flex: 1, backgroundColor: '#161616' },
  metaHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, backgroundColor: '#1A1A1A', borderBottomWidth: 1, borderBottomColor: '#333' },
  metaHeaderTitle: { color: '#FFF', fontSize: 20, fontWeight: 'bold' },
  metaScroll: { flex: 1, padding: 20 },
  metaInfoText: { color: '#FF9800', fontSize: 14, marginBottom: 20, fontWeight: 'bold' },
  metaInputGroup: { backgroundColor: '#222', borderRadius: 8, padding: 10, marginBottom: 15, borderBottomWidth: 1, borderBottomColor: '#444' },
  metaInputGroupDisabled: { backgroundColor: '#1A1A1A', borderRadius: 8, padding: 10, marginBottom: 15 },
  metaLabel: { color: '#888', fontSize: 12, marginBottom: 5 },
  metaInput: { color: '#FFF', fontSize: 16, padding: 0 },
  metaTextDisabled: { color: '#555', fontSize: 16, marginTop: 5 },
  // === ESTILOS DO REPRODUTOR LRC (NOVO) ===
  lrcPlayerContainer: { flex: 1, backgroundColor: '#121212', width: '100%' },
  lrcSelectionArea: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  lrcSelectionTitle: { fontSize: 24, fontWeight: 'bold', color: '#FFF', marginBottom: 10, textAlign: 'center' },
  lrcSelectionSub: { fontSize: 14, color: '#A0A0A0', textAlign: 'center', marginBottom: 30 },
  lrcSelectBtn: { flexDirection: 'row', backgroundColor: '#FF9800', width: '80%', paddingVertical: 15, borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginBottom: 15, elevation: 3 },
  lrcSelectBtnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
  
  lrcPlayingArea: { flex: 1, width: '100%', justifyContent: 'space-between' },
  lrcMusicHeader: { flexDirection: 'row', alignItems: 'center', padding: 15, backgroundColor: '#1A1A1A', borderBottomWidth: 1, borderBottomColor: '#333' },
  lrcAlbumArt: { width: 60, height: 60, borderRadius: 8, backgroundColor: '#2A2A2A', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  lrcMusicInfo: { flex: 1 },
  lrcMusicTitle: { color: '#FFF', fontSize: 18, fontWeight: 'bold' },
  lrcMusicArtist: { color: '#FF9800', fontSize: 14, marginTop: 2 },
  lrcMusicAlbum: { color: '#777', fontSize: 12, marginTop: 2 },
  
  lrcLyricsList: { flex: 1, width: '100%', paddingHorizontal: 20 },
  lrcLyricLine: { color: '#777', fontSize: 18, textAlign: 'center', marginVertical: 12, fontWeight: '500' },
  lrcLyricLineActive: { color: '#FFF', fontSize: 24, fontWeight: 'bold', textShadowColor: 'rgba(255, 152, 0, 0.6)', textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 10 },
  
  lrcBottomControlBar: { backgroundColor: '#1A1A1A', paddingVertical: 15, paddingHorizontal: 20, borderTopWidth: 1, borderTopColor: '#333' },
  lrcSliderContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  lrcTimeText: { color: '#A0A0A0', fontSize: 12, width: 45, textAlign: 'center' },
  lrcSlider: { flex: 1, height: 40, marginHorizontal: 10 },
  lrcButtonsContainer: { flexDirection: 'row', justifyContent: 'space-evenly', alignItems: 'center', paddingHorizontal: 30 },
  lrcPlayBtnMain: { width: 65, height: 65, borderRadius: 35, backgroundColor: '#FF9800', justifyContent: 'center', alignItems: 'center', elevation: 5 },
  // === ESTILOS DO PAINEL INFERIOR (BOTTOM TAB BAR) ===
  bottomTabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#0A0A0A',
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderTopWidth: 1,
    borderTopColor: '#222',
  },
  bottomTabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
  }
});